################################################################################
#                             basic build file                                 #
################################################################################
OBJS = application_properties init_app init_board init_mcu pti sl_sleeptimer sl_sleeptimer_hal_rtcc mx25flash_spi retargetserial retargetio 

include ../../common.mk
