################################################################################
#                             basic build file                                 #
################################################################################
OBJS = arm_sin_cos_example_f32 arm_add_f32 arm_mult_f32 arm_cos_f32 arm_sin_f32 arm_common_tables

include ../../common.mk
