################################################################################
#                             basic build file                                 #
################################################################################
OBJS = em_assert em_burtc em_cmu em_core em_cryotimer em_crypto em_emu em_eusart em_gpio em_i2c em_iadc em_ldma em_msc em_pdm em_rmu em_rtcc em_se em_system em_timer em_usart em_letimer

include ../../common.mk
