################################################################################
#                             basic build file                                 #
################################################################################
OBJS = main app dcd mesh_pstore gatt_db mesh_lib led_driver led_control light_controller lightbulb scheduler time scenes mesh_sensor mesh_serdeser 
include ../../../common.mk
